apiVersion: v1
kind: Service
metadata:
  name: sae-frontend-svc
  namespace: gufy
  labels:
    app: sae-frontend
spec:
  type: ClusterIP  # 只需要 Ingress 访问，不需要对外暴露 NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: sae-frontend
